pull_request_rules:
  - name: Merge pull requests from develop branch to release/* branches
    conditions:
      - base=release/*
      - head=develop
    actions:
      merge:
        method: rebase # You can choose "squash", "rebase", or "merge" based on your preferred merge method
