name: Only Let Release Branches Merge Into Main

on:
  pull_request:
    branches:
      - main

jobs:
  check_base_branch:
    runs-on: ubuntu-latest
    steps:
      - name: Fail if PR is from develop branch
        run: |
          if [[ "${{ github.event.pull_request.head.ref }}" =~ ^release/.* ]]; then
            exit 0
          else
            echo "Error: Merging from a branch that doesn't start with 'release/' into the 'main' branch is not allowed."
            exit 1
          fi
